### ISSUE TITLE
Support port 80/443 (or custom?) for server_info

### ISSUE THREAD

**Issue by alt4** [HALOMAXX/BLREdit#37]
Hello,

I was testing a build made from the latest commit as of writing (12c9a7a) and was pretty happy to notice that you were planning to support the `/server_info` API endpoint from server-utils, however I've noticed that BLREdit only tries to connect to port 7778 for said endpoint, unlike MagicCow's `/api/server` which is expected on port 80:

```
[22/12/2022 02:29:41]: [Server](http://blrevive.northamp.fr:7778/server_info): System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BLREdit.API.REST_API.Server.ServerUtilsClient.<GetAsync>d__0.MoveNext() in D:\a\BLREdit\BLREdit\BLREdit\API\REST_API\Server\ServerUtilsClient.cs:line 20
[22/12/2022 02:29:41]: [Server](NotFound): GET http://blrevive.northamp.fr/api/server
 
[22/12/2022 02:29:41]: FoxEntry
[22/12/2022 02:34:15]: [Server](http://blrevive.northamp.fr:7778/server_info): System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BLREdit.API.REST_API.Server.ServerUtilsClient.<GetAsync>d__0.MoveNext() in D:\a\BLREdit\BLREdit\BLREdit\API\REST_API\Server\ServerUtilsClient.cs:line 20
[22/12/2022 02:34:15]: [Server](NotFound): GET http://blrevive.northamp.fr/api/server
 
[22/12/2022 02:34:15]: FoxEntry
```

I cannot easily expose an API on port 7778 (due to various networking/firewalling constraints), and was planning to expose the endpoint on ports [80](http://blrevive.northamp.fr/server_info) and [443](https://blrevive.northamp.fr/server_info) instead (with http and https schemes respectively).

Would it be possible to poll at least one of these ports as well as 7778, or make it configurable by the client?

**Comment by HALOMAXX** [comment]
I added the setting to BLRedit here is a Screenshot 
![image](https://user-images.githubusercontent.com/12860407/209054259-c4b50ffb-6d7e-4162-80da-f11a9dd863d0.png)

**Comment by alt4** [comment]
Excellent, that was fast!

Thanks
